### ISSUE TITLE
Installing failed on Atom 1.24.0

### ISSUE THREAD

**Issue by Sonic0** [shirogaku/nodemcu-lua-snippets#1]
I have an error when i try to install this package:

> Installing “nodemcu-lua-snippets@0.1.3” failed.Hide output…
> (node:4348)    [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by shirogaku** [comment]
@Sonic0 Check this out.
https://github.com/atom/apm/issues/680
